import type { FinancialDataset } from "@/lib/finance";

export const sampleData: FinancialDataset = {
  revenueRecords: [
    {
      id: "rev-1",
      date: "2026-05-08",
      customer: "Amazon",
      description: "Regional delivery settlement",
      category: "Amazon",
      amount: 43800,
      invoiceNumber: "AMZ-0508",
      truckId: "truck-1",
      driverId: "driver-1",
    },
    {
      id: "rev-2",
      date: "2026-05-20",
      customer: "Load Board",
      description: "Brokered backhaul loads",
      category: "Load Board",
      amount: 12800,
      invoiceNumber: "LB-0520",
      truckId: "truck-2",
      driverId: "driver-2",
    },
    {
      id: "rev-3",
      date: "2026-06-09",
      customer: "Amazon",
      description: "Dedicated lanes",
      category: "Amazon",
      amount: 45200,
      invoiceNumber: "AMZ-0609",
      truckId: "truck-1",
      driverId: "driver-1",
    },
    {
      id: "rev-4",
      date: "2026-06-25",
      customer: "Other Customers",
      description: "Cross-dock work",
      category: "Other Customers",
      amount: 14800,
      invoiceNumber: "OTH-0625",
      truckId: "truck-3",
      driverId: "driver-3",
    },
    {
      id: "rev-5",
      date: "2026-07-10",
      customer: "Amazon",
      description: "Prime lanes",
      category: "Amazon",
      amount: 41800,
      invoiceNumber: "AMZ-0710",
      truckId: "truck-1",
      driverId: "driver-1",
    },
    {
      id: "rev-6",
      date: "2026-07-21",
      customer: "Load Board",
      description: "Overflow spot market freight",
      category: "Load Board",
      amount: 13200,
      invoiceNumber: "LB-0721",
      truckId: "truck-2",
      driverId: "driver-2",
    },
    {
      id: "rev-7",
      date: "2026-08-06",
      customer: "Amazon",
      description: "August settlements",
      category: "Amazon",
      amount: 40200,
      invoiceNumber: "AMZ-0806",
      truckId: "truck-1",
      driverId: "driver-1",
    },
    {
      id: "rev-8",
      date: "2026-08-09",
      customer: "Other Customers",
      description: "Customer shuttle runs",
      category: "Other Customers",
      amount: 11200,
      invoiceNumber: "OTH-0809",
      truckId: "truck-3",
      driverId: "driver-3",
    },
  ],
  expenseRecords: [
    {
      id: "exp-1",
      date: "2026-05-03",
      vendor: "ADP",
      description: "Payroll batch",
      amount: 20100,
      category: "Payroll",
      paymentAccount: "Chase Business Checking",
      recurring: true,
      fixed: false,
      source: "ADP import",
      transactionId: "adp-0503",
      driverId: "driver-1",
    },
    {
      id: "exp-2",
      date: "2026-05-05",
      vendor: "Love's",
      description: "Fuel fill-up",
      amount: 8500,
      category: "Fuel",
      paymentAccount: "Chase Business Credit Card",
      recurring: true,
      fixed: false,
      source: "Bank import",
      transactionId: "fuel-0505",
      truckId: "truck-1",
      driverId: "driver-1",
    },
    {
      id: "exp-3",
      date: "2026-05-11",
      vendor: "Progressive",
      description: "Commercial insurance",
      amount: 6900,
      category: "Insurance",
      paymentAccount: "Chase Business Checking",
      recurring: true,
      fixed: true,
      source: "Bank import",
      transactionId: "ins-0511",
    },
    {
      id: "exp-4",
      date: "2026-05-15",
      vendor: "Fleetio",
      description: "Fleet software",
      amount: 980,
      category: "Software",
      paymentAccount: "Chase Business Credit Card",
      recurring: true,
      fixed: true,
      source: "Bank import",
      transactionId: "sft-0515",
    },
    {
      id: "exp-5",
      date: "2026-05-18",
      vendor: "Shop Repair Co",
      description: "Maintenance work order",
      amount: 2100,
      category: "Maintenance",
      paymentAccount: "Chase Business Checking",
      recurring: false,
      fixed: false,
      source: "Bank import",
      transactionId: "mnt-0518",
      truckId: "truck-2",
    },
    {
      id: "exp-6",
      date: "2026-06-03",
      vendor: "ADP",
      description: "Payroll batch",
      amount: 21200,
      category: "Payroll",
      paymentAccount: "Chase Business Checking",
      recurring: true,
      fixed: false,
      source: "ADP import",
      transactionId: "adp-0603",
      driverId: "driver-1",
    },
    {
      id: "exp-7",
      date: "2026-06-04",
      vendor: "Love's",
      description: "Fuel fill-up",
      amount: 8900,
      category: "Fuel",
      paymentAccount: "Chase Business Credit Card",
      recurring: true,
      fixed: false,
      source: "Bank import",
      transactionId: "fuel-0604",
      truckId: "truck-1",
      driverId: "driver-1",
    },
    {
      id: "exp-8",
      date: "2026-06-11",
      vendor: "Progressive",
      description: "Commercial insurance",
      amount: 6900,
      category: "Insurance",
      paymentAccount: "Chase Business Checking",
      recurring: true,
      fixed: true,
      source: "Bank import",
      transactionId: "ins-0611",
    },
    {
      id: "exp-9",
      date: "2026-06-15",
      vendor: "Fleetio",
      description: "Fleet software",
      amount: 980,
      category: "Software",
      paymentAccount: "Chase Business Credit Card",
      recurring: true,
      fixed: true,
      source: "Bank import",
      transactionId: "sft-0615",
    },
    {
      id: "exp-10",
      date: "2026-06-20",
      vendor: "Shop Repair Co",
      description: "Maintenance work order",
      amount: 2400,
      category: "Maintenance",
      paymentAccount: "Chase Business Checking",
      recurring: false,
      fixed: false,
      source: "Bank import",
      transactionId: "mnt-0620",
      truckId: "truck-2",
    },
    {
      id: "exp-11",
      date: "2026-07-03",
      vendor: "ADP",
      description: "Payroll batch",
      amount: 22800,
      category: "Payroll",
      paymentAccount: "Chase Business Checking",
      recurring: true,
      fixed: false,
      source: "ADP import",
      transactionId: "adp-0703",
      driverId: "driver-1",
    },
    {
      id: "exp-12",
      date: "2026-07-05",
      vendor: "Love's",
      description: "Fuel fill-up",
      amount: 9800,
      category: "Fuel",
      paymentAccount: "Chase Business Credit Card",
      recurring: true,
      fixed: false,
      source: "Bank import",
      transactionId: "fuel-0705",
      truckId: "truck-1",
      driverId: "driver-1",
    },
    {
      id: "exp-13",
      date: "2026-07-11",
      vendor: "Progressive",
      description: "Commercial insurance",
      amount: 7100,
      category: "Insurance",
      paymentAccount: "Chase Business Checking",
      recurring: true,
      fixed: true,
      source: "Bank import",
      transactionId: "ins-0711",
    },
    {
      id: "exp-14",
      date: "2026-07-15",
      vendor: "Fleetio",
      description: "Fleet software",
      amount: 1120,
      category: "Software",
      paymentAccount: "Chase Business Credit Card",
      recurring: true,
      fixed: true,
      source: "Bank import",
      transactionId: "sft-0715",
    },
    {
      id: "exp-15",
      date: "2026-07-22",
      vendor: "Shop Repair Co",
      description: "Brake and suspension repair",
      amount: 3800,
      category: "Maintenance",
      paymentAccount: "Chase Business Checking",
      recurring: false,
      fixed: false,
      source: "Bank import",
      transactionId: "mnt-0722",
      truckId: "truck-2",
    },
    {
      id: "exp-16",
      date: "2026-08-03",
      vendor: "ADP",
      description: "Payroll batch",
      amount: 26900,
      category: "Payroll",
      paymentAccount: "Chase Business Checking",
      recurring: true,
      fixed: false,
      source: "ADP import",
      transactionId: "adp-0803",
      driverId: "driver-1",
    },
    {
      id: "exp-17",
      date: "2026-08-04",
      vendor: "Love's",
      description: "Fuel fill-up",
      amount: 11100,
      category: "Fuel",
      paymentAccount: "Chase Business Credit Card",
      recurring: true,
      fixed: false,
      source: "Bank import",
      transactionId: "fuel-0804",
      truckId: "truck-1",
      driverId: "driver-1",
    },
    {
      id: "exp-18",
      date: "2026-08-11",
      vendor: "Progressive",
      description: "Commercial insurance",
      amount: 7300,
      category: "Insurance",
      paymentAccount: "Chase Business Checking",
      recurring: true,
      fixed: true,
      source: "Bank import",
      transactionId: "ins-0811",
    },
    {
      id: "exp-19",
      date: "2026-08-14",
      vendor: "Fleetio",
      description: "Fleet software",
      amount: 1720,
      category: "Software",
      paymentAccount: "Chase Business Credit Card",
      recurring: true,
      fixed: true,
      source: "Bank import",
      transactionId: "sft-0814",
    },
    {
      id: "exp-20",
      date: "2026-08-21",
      vendor: "Shop Repair Co",
      description: "Transmission work",
      amount: 6100,
      category: "Maintenance",
      paymentAccount: "Chase Business Checking",
      recurring: false,
      fixed: false,
      source: "Bank import",
      transactionId: "mnt-0821",
      truckId: "truck-2",
    },
  ],
  accounts: [
    { id: "acct-1", name: "Chase Business Checking", type: "Checking", balance: 29800 },
    { id: "acct-2", name: "Chase Business Credit Card", type: "Credit Card", balance: -12400 },
    { id: "acct-3", name: "Loan Account", type: "Liability", balance: -98600 },
  ],
  vendorRules: [
    { id: "rule-1", matchText: "ADP", category: "Payroll", rationale: "Payroll processor" },
    { id: "rule-2", matchText: "Love's", category: "Fuel", rationale: "Fuel vendor" },
    { id: "rule-3", matchText: "Fleetio", category: "Software", rationale: "Fleet management" },
    { id: "rule-4", matchText: "Indeed", category: "Recruiting", rationale: "Hiring vendor" },
  ],
  importHistory: [
    {
      id: "imp-1",
      fileName: "chase-checking-july.csv",
      importedAt: "2026-08-02",
      transactionCount: 63,
      imported: 57,
      skipped: 2,
      duplicates: 3,
      requiringReview: 1,
    },
    {
      id: "imp-2",
      fileName: "adp-payroll-2026-07.xlsx",
      importedAt: "2026-08-03",
      transactionCount: 11,
      imported: 11,
      skipped: 0,
      duplicates: 0,
      requiringReview: 0,
    },
  ],
  budgets: [
    { category: "Fuel", month: "2026-08", amount: 10000 },
    { category: "Payroll", month: "2026-08", amount: 24000 },
    { category: "Insurance", month: "2026-08", amount: 7000 },
    { category: "Maintenance", month: "2026-08", amount: 4000 },
    { category: "Software", month: "2026-08", amount: 1200 },
  ],
  drivers: [
    { id: "driver-1", name: "Driver A" },
    { id: "driver-2", name: "Driver B" },
    { id: "driver-3", name: "Driver C" },
  ],
  trucks: [
    { id: "truck-1", number: "Truck 1" },
    { id: "truck-2", number: "Truck 2" },
    { id: "truck-3", number: "Truck 3" },
  ],
};
